### ISSUE TITLE
pysgpp fails to import on linux

### ISSUE THREAD

**Issue by maierbn** [SGpp/SGpp#238]
Hi,

I can't get the pysgpp module to work:

Using the `.whl` from the latest release gives this error:
```
$ ./bin/pip3 install pysgpp-3.3.0-py3-none-linux_x86_64.whl
Processing ./pysgpp-3.3.0-py3-none-linux_x86_64.whl
Installing collected packages: pysgpp
Successfully installed pysgpp-3.3.0
$ ./bin/python3
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysgpp
*** stack smashing detected ***: terminated
Aborted
```

Using the pip repo does not work either:
```
$ ./bin/python3 -m pip install pysgpp --prefix=/usr/local.nfs/sgs/software/python/3.8.5/                                                                                                         Collecting pysgpp                                                                                                                                                                             
  Downloading pysgpp-3.3.1-py3-none-manylinux2010_x86_64.whl (8.7 MB)                                                                                                                              |████████████████████████████████| 8.7 MB 7.5 MB/s                                                                                                                                       Installing collected packages: pysgpp                                                                                                                                                         Successfully installed pysgpp-3.3.1     
$ ./bin/python3                                                                                                                                                                                  
Python 3.8.2 (default, Jul 16 2020, 14:00:26)                                                                                                                                                 
[GCC 9.3.0] on linux                                                                                                                                                                          
Type "help", "copyright", "credits" or "license" for more information.                                                                                                                        
>>> import pysgpp                                                                                                                                                                             
Traceback (most recent call last):                                                                                                                                                            
  File "/import/sgs.local/software/python/3.8.5/lib/python3.8/site-packages/numpy/__init__.py", line 142, in <module>                                                                         
    from . import core                                                                                                                                                                        
  File "/import/sgs.local/software/python/3.8.5/lib/python3.8/site-packages/numpy/core/__init__.py", line 102, in <module>                                                                    
    from . import _dtype_ctypes                                                                                                                                                               
  File "/import/sgs.local/software/python/3.8.5/lib/python3.8/site-packages/numpy/core/_dtype_ctypes.py", line 25, in <module>                                                                
    import _ctypes                                                                                                                                                                            
ImportError: libffi.so.6: cannot open shared object file: No such file or directory                                                                                                           
Traceback (most recent call last):                                                                                                                                                            
  File "<stdin>", line 1, in <module>                                                                                                                                                         
  File "/import/sgs.local/software/python/3.8.5/lib/python3.8/site-packages/pysgpp/__init__.py", line 8, in <module>                                                                          
    from .pysgpp_swig import *                                                                                                                                                                
  File "/import/sgs.local/software/python/3.8.5/lib/python3.8/site-packages/pysgpp/pysgpp_swig.py", line 11, in <module>                                                                      
    from . import _pysgpp_swig                                                                                                                                                                
ImportError: numpy.core.multiarray failed to import                                                                                                                                           
>>>                
```

**Comment by maierbn** [comment]
The system runs Ubuntu 20.04 (our neon server) in case that's relevant.
```
$ uname -a
Linux neon 5.4.0-45-generic #49-Ubuntu SMP Wed Aug 26 13:38:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by maierbn** [comment]
The version 3.3.1 in the pip repo works, however, after installing libffi:
```
$ module load libffi 
$ ./bin/python3
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysgpp
>>> 
```

**Comment by spc90** [comment]
This seems to be a larger issue with Ubuntu 20.04, which uses libffi7, whereas our packages use libffi6. This is pointed out also [here](https://github.com/im-tomu/fomu-toolchain/issues/16), with some possible fixes mentioned [in this comment](https://github.com/im-tomu/fomu-toolchain/issues/16#issuecomment-698343850).

In the meanwhile loading/installing libffi6 as shown above should normally fix the issue in the current releases, until a proper solution is implemented int he new releases.
