### ISSUE TITLE
Dataset tests failing on master_gitlab

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [SGpp/SGpp#89]
pull request #81 introduced some paths errors in the python tests, which we fixed in the feature_python3 branch with a36136e9ba4ed09d2c34778e65674b87e019acc0 . Now however, we are left with some actual data errors.
```
$ python3 datadriven/tests/test_datadriven.py 
[...]
======================================================================
ERROR: testLearnDataWithFolding (tbin.tlearner.test_Classifier.TestClassifier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/scratch/pollinta/SGpp/datadriven/tests/tbin/tlearner/test_Classifier.py", line 138, in testLearnDataWithFolding
    dataContainer = ARFFAdapter(pathlocal + "/../../../datasets/liver-disorders_normalized.arff").loadData()
  File "/data/scratch/pollinta/SGpp/lib/pysgpp/extensions/datadriven/data/ARFFAdapter.py", line 84, in loadData
    fin = self.__gzOpen(self.filename, "r")
  File "/data/scratch/pollinta/SGpp/lib/pysgpp/extensions/datadriven/data/ARFFAdapter.py", line 174, in __gzOpen
    fd = open(filename, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/data/scratch/pollinta/SGpp/datadriven/tests/tbin/tlearner/../../../datasets/liver-disorders_normalized.arff'

======================================================================
ERROR: testLoadData (tbin.tdata.test_ARFFAdapter.TestARFFAdapter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/scratch/pollinta/SGpp/datadriven/tests/tbin/tdata/test_ARFFAdapter.py", line 105, in testLoadData
    points.getRow(rowIdx, testVector)
  File "/data/scratch/pollinta/SGpp/lib/pysgpp/pysgpp_swig.py", line 1747, in getRow
    return _pysgpp_swig.DataMatrix_getRow(self, row, vec)
RuntimeError: DataMatrix::getRow : Dimensions do not match

======================================================================
FAIL: testLoadSpecification (tbin.tdata.test_ARFFAdapter.TestARFFAdapter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/scratch/pollinta/SGpp/datadriven/tests/tbin/tdata/test_ARFFAdapter.py", line 124, in testLoadSpecification
    self.assertEqual(len(testAttributes), len(attributes))
AssertionError: 7 != 4

----------------------------------------------------------------------
Ran 21 tests in 0.127s
```
The test seemingly expects 4 columns of data, but the file contains 7. Do you know more about this @krsgpp ?

**Comment by krsgpp** [comment]
Should be fixed in2f1ed0a (I pushed the commit directly to master_gitlab). I'm not 100% sure that is fixes the problem because the python stuff is currently not running on my machine.
